/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;


import DAO.produtosDAO;
import Model.Cliente;
import Model.Produto;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author guilh
 */
public class BuscaProdutos extends javax.swing.JInternalFrame {

    Produto objProduto;

    /**
     * Creates new form BuscaProdutos
     */
    public BuscaProdutos() {
        initComponents();
          objProduto = new Produto();
        CarregarJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblBuscaProdutos = new javax.swing.JTable();

        tblBuscaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo Produto", "Nome", "Valor"
            }
        ));
        jScrollPane1.setViewportView(tblBuscaProdutos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBuscaProdutos;
    // End of variables declaration//GEN-END:variables

   public void CarregarJTable() {
        

        ArrayList<Produto> listaProduto = produtosDAO.consultarProdutos(title);

        DefaultTableModel tmProdutos = new DefaultTableModel();
        tmProdutos.addColumn("Codigo Produto");
        tmProdutos.addColumn("Nome");
        tmProdutos.addColumn("Valor");
       

        tblBuscaProdutos.setModel(tmProdutos);

        tmProdutos.setRowCount(0);
        tmProdutos.addRow(new Object[]{objProduto.getCodigo(), objProduto.getDescricao(), objProduto.getPreco()});
//        }

        for (Produto p : listaProduto) {
            tmProdutos.addRow(new Object[]{p.getCodigo(), p.getDescricao(), p.getPreco()});
        }

     
        tblBuscaProdutos.getColumnModel().getColumn(0).setPreferredWidth(35); // Nome
        tblBuscaProdutos.getColumnModel().getColumn(1).setPreferredWidth(200); //CPF
         tblBuscaProdutos.getColumnModel().getColumn(2).setPreferredWidth(250); //Valor
    }
}
