/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author guilh
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmArquivo = new javax.swing.JMenu();
        jmiSair = new javax.swing.JMenuItem();
        jmClientes = new javax.swing.JMenu();
        jmiCadastrar = new javax.swing.JMenuItem();
        jmiPesq = new javax.swing.JMenuItem();
        jmUsuarios = new javax.swing.JMenu();
        jmiCadUsu = new javax.swing.JMenuItem();
        jmiPesqUsu = new javax.swing.JMenuItem();
        jmProdutos = new javax.swing.JMenu();
        jmiCadProd = new javax.swing.JMenuItem();
        jmiConsuProd = new javax.swing.JMenuItem();
        jmSobre = new javax.swing.JMenu();
        jmiSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton1.setText("Vender");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jmArquivo.setText("Arquivo");

        jmiSair.setText("Sair");
        jmiSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSairActionPerformed(evt);
            }
        });
        jmArquivo.add(jmiSair);

        jMenuBar1.add(jmArquivo);

        jmClientes.setText("Clientes");

        jmiCadastrar.setText("Cadastrar");
        jmiCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastrarActionPerformed(evt);
            }
        });
        jmClientes.add(jmiCadastrar);

        jmiPesq.setText("Consulta");
        jmiPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPesqActionPerformed(evt);
            }
        });
        jmClientes.add(jmiPesq);

        jMenuBar1.add(jmClientes);

        jmUsuarios.setText("Usuarios");
        jmUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmUsuariosActionPerformed(evt);
            }
        });

        jmiCadUsu.setText("Cadastro");
        jmUsuarios.add(jmiCadUsu);

        jmiPesqUsu.setText("Pesquisar");
        jmUsuarios.add(jmiPesqUsu);

        jMenuBar1.add(jmUsuarios);

        jmProdutos.setText("Produtos");

        jmiCadProd.setText("Cadastrar Produto");
        jmiCadProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadProdActionPerformed(evt);
            }
        });
        jmProdutos.add(jmiCadProd);

        jmiConsuProd.setText("Consultar Produto");
        jmProdutos.add(jmiConsuProd);

        jMenuBar1.add(jmProdutos);

        jmSobre.setText("Sobre");

        jmiSobre.setText("Sobre");
        jmSobre.add(jmiSobre);

        jMenuBar1.add(jmSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jButton1)
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jButton1)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmiSairActionPerformed

    private void jmiCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastrarActionPerformed
        new TelaCadastroCliente().setVisible(true);
    }//GEN-LAST:event_jmiCadastrarActionPerformed

    private void jmiCadProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadProdActionPerformed
        new TelaCadastroProduto().setVisible(true);
    }//GEN-LAST:event_jmiCadProdActionPerformed

    private void jmUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmUsuariosActionPerformed

    }//GEN-LAST:event_jmUsuariosActionPerformed

    private void jmiPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPesqActionPerformed
        new TelaConsultaCliente().setVisible(true);
    }//GEN-LAST:event_jmiPesqActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       new TelaVendas().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmArquivo;
    private javax.swing.JMenu jmClientes;
    private javax.swing.JMenu jmProdutos;
    private javax.swing.JMenu jmSobre;
    private javax.swing.JMenu jmUsuarios;
    private javax.swing.JMenuItem jmiCadProd;
    private javax.swing.JMenuItem jmiCadUsu;
    private javax.swing.JMenuItem jmiCadastrar;
    private javax.swing.JMenuItem jmiConsuProd;
    private javax.swing.JMenuItem jmiPesq;
    private javax.swing.JMenuItem jmiPesqUsu;
    private javax.swing.JMenuItem jmiSair;
    private javax.swing.JMenuItem jmiSobre;
    // End of variables declaration//GEN-END:variables
}
